name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker compose up and build
      run: docker-compose up -d
    - name: run tests
      run: docker exec backend sh -c "pytest ."
